/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIConversationSummary {
  'id' : bigint,
  'title' : string,
  'lastMessageAt' : Timestamp,
  'messageCount' : bigint,
}
export type BlogId = bigint;
export type BlogSort = { 'mostBookmarked' : null } |
  { 'newest' : null } |
  { 'mostLiked' : null } |
  { 'mostViewed' : null };
export interface BlogView {
  'id' : BlogId,
  'title' : string,
  'likeCount' : bigint,
  'content' : string,
  'published' : boolean,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'author' : Principal,
  'updatedAt' : Timestamp,
  'viewCount' : bigint,
  'excerpt' : string,
  'coverImageBlobId' : [] | [Uint8Array],
}
export interface BookmarkItem {
  'content' : ContentRef,
  'bookmarkedAt' : Timestamp,
}
export type Category = string;
export type CommentId = bigint;
export interface CommentView {
  'id' : CommentId,
  'likeCount' : bigint,
  'content' : string,
  'parentCommentId' : [] | [CommentId],
  'createdAt' : Timestamp,
  'author' : Principal,
  'blogId' : BlogId,
}
export interface ContentPerformanceItem {
  'id' : bigint,
  'title' : string,
  'trend' : bigint,
  'contentType' : ContentType,
  'views' : bigint,
  'likes' : bigint,
  'comments' : bigint,
}
export interface ContentRef {
  'id' : bigint,
  'title' : string,
  'contentType' : ContentType,
  'author' : Principal,
}
export type ContentType = { 'video' : null } |
  { 'blog' : null } |
  { 'note' : null };
export interface Conversation {
  'id' : bigint,
  'title' : string,
  'createdAt' : Timestamp,
  'user' : UserId,
  'updatedAt' : Timestamp,
}
export interface CreatorDashboard {
  'contentPerformance' : Array<ContentPerformanceItem>,
  'viewsOverTime' : Array<CreatorViewsByTypePoint>,
  'recentComments' : Array<RecentCommentItem>,
  'engagementByType' : Array<EngagementByType>,
  'totals' : CreatorTotals,
}
export interface CreatorTotals {
  'contentCount' : bigint,
  'totalBookmarks' : bigint,
  'totalViews' : bigint,
  'totalLikes' : bigint,
}
export interface CreatorViewsByTypePoint {
  'videoViews' : bigint,
  'date' : string,
  'noteViews' : bigint,
  'blogViews' : bigint,
}
export interface EngagementByType {
  'contentType' : ContentType,
  'bookmarks' : bigint,
  'likes' : bigint,
  'comments' : bigint,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface ListBlogsQuery {
  'tag' : [] | [string],
  'page' : bigint,
  'sort' : BlogSort,
  'pageSize' : bigint,
  'search' : [] | [string],
}
export interface ListBlogsResult {
  'total' : bigint,
  'page' : bigint,
  'pageSize' : bigint,
  'items' : Array<BlogView>,
}
export interface ListNotificationsResult {
  'unreadCount' : bigint,
  'items' : Array<NotificationView>,
}
export interface Message {
  'id' : bigint,
  'content' : string,
  'createdAt' : Timestamp,
  'role' : MessageRole,
  'conversationId' : bigint,
  'sources' : Array<SourceReference>,
}
export type MessageRole = { 'user' : null } |
  { 'assistant' : null };
export type NoteFileType = { 'pdf' : null } |
  { 'ppt' : null } |
  { 'zip' : null } |
  { 'docx' : null };
export interface NoteInput {
  'title' : string,
  'subject' : string,
  'published' : boolean,
  'description' : string,
  'fileSize' : bigint,
  'fileType' : NoteFileType,
  'blobId' : string,
}
export interface NoteListQuery {
  'subject' : [] | [string],
  'page' : bigint,
  'sort' : [] | [NoteSort],
  'pageSize' : bigint,
  'search' : [] | [string],
  'fileType' : [] | [NoteFileType],
}
export interface NoteListResult {
  'total' : bigint,
  'page' : bigint,
  'pageSize' : bigint,
  'items' : Array<NoteView>,
}
export type NoteSort = { 'mostBookmarked' : null } |
  { 'mostDownloaded' : null } |
  { 'newest' : null } |
  { 'mostLiked' : null };
export interface NoteUpdate {
  'title' : [] | [string],
  'subject' : [] | [string],
  'published' : [] | [boolean],
  'description' : [] | [string],
  'fileSize' : [] | [bigint],
  'fileType' : [] | [NoteFileType],
  'blobId' : [] | [string],
}
export interface NoteView {
  'id' : bigint,
  'title' : string,
  'likeCount' : bigint,
  'subject' : string,
  'published' : boolean,
  'createdAt' : bigint,
  'description' : string,
  'fileSize' : bigint,
  'fileType' : NoteFileType,
  'author' : Principal,
  'updatedAt' : bigint,
  'blobId' : string,
  'downloadCount' : bigint,
}
export type NotificationId = bigint;
export type NotificationType = { 'like' : null } |
  { 'systemMessage' : null } |
  { 'comment' : null } |
  { 'roleUpgrade' : null } |
  { 'moderation' : null };
export interface NotificationView {
  'id' : NotificationId,
  'content' : string,
  'source' : [] | [SourceContent],
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'read' : boolean,
  'recipient' : Principal,
}
export interface RecentCommentItem {
  'contentId' : bigint,
  'content' : string,
  'commentId' : bigint,
  'contentType' : ContentType,
  'createdAt' : Timestamp,
  'author' : Principal,
  'contentTitle' : string,
}
export interface Recommendation {
  'contentRef' : {
    'id' : bigint,
    'title' : string,
    'contentType' : { 'video' : null } |
      { 'blog' : null } |
      { 'note' : null },
    'author' : Principal,
  },
  'score' : number,
  'reason' : string,
}
export type Result = { 'ok' : null } |
  { 'err' : Error };
export interface SendMessageResult {
  'message' : Message,
  'sources' : Array<SourceReference>,
}
export interface SourceContent { 'id' : bigint, 'contentType' : string }
export interface SourceReference {
  'title' : string,
  'contentId' : bigint,
  'sourceType' : SourceType,
}
export type SourceType = { 'video' : null } |
  { 'blog' : null } |
  { 'note' : null };
export interface StudentActivityPoint {
  'date' : string,
  'bookmarks' : bigint,
  'likes' : bigint,
  'aiSessions' : bigint,
}
export interface StudentDashboard {
  'bookmarks' : Array<BookmarkItem>,
  'recentAIConversations' : Array<AIConversationSummary>,
  'totals' : StudentTotals,
  'learningActivityOverTime' : Array<StudentActivityPoint>,
}
export interface StudentTotals {
  'aiConversationsCount' : bigint,
  'likedContentCount' : bigint,
  'bookmarksCount' : bigint,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface TrendingItem {
  'views' : bigint,
  'contentRef' : {
    'id' : bigint,
    'title' : string,
    'contentType' : { 'video' : null } |
      { 'blog' : null } |
      { 'note' : null },
    'author' : Principal,
  },
  'likes' : bigint,
  'score' : number,
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : VideoId,
  'title' : string,
  'likeCount' : bigint,
  'isShort' : boolean,
  'videoBlobId' : string,
  'thumbnailBlobId' : string,
  'published' : boolean,
  'createdAt' : bigint,
  'description' : string,
  'author' : Principal,
  'updatedAt' : bigint,
  'viewCount' : bigint,
  'durationSeconds' : bigint,
  'category' : Category,
}
export interface VideoFilter {
  'isShort' : [] | [boolean],
  'page' : [] | [bigint],
  'sort' : [] | [VideoSort],
  'pageSize' : [] | [bigint],
  'search' : [] | [string],
  'category' : [] | [Category],
}
export type VideoId = bigint;
export interface VideoInput {
  'title' : string,
  'isShort' : boolean,
  'videoBlobId' : string,
  'thumbnailBlobId' : string,
  'published' : boolean,
  'description' : string,
  'durationSeconds' : bigint,
  'category' : Category,
}
export interface VideoPage {
  'total' : bigint,
  'page' : bigint,
  'pageSize' : bigint,
  'items' : Array<Video>,
}
export type VideoSort = { 'mostBookmarked' : null } |
  { 'newest' : null } |
  { 'mostLiked' : null } |
  { 'mostViewed' : null };
export interface VideoUpdate {
  'title' : [] | [string],
  'isShort' : [] | [boolean],
  'thumbnailBlobId' : [] | [string],
  'published' : [] | [boolean],
  'description' : [] | [string],
  'category' : [] | [Category],
}
export interface _SERVICE {
  '__accessControlState' : ActorMethod<[], any>,
  '__blogBookmarks' : ActorMethod<[], any>,
  '__blogLikes' : ActorMethod<[], any>,
  '__blogs' : ActorMethod<[], any>,
  '__commentLikes' : ActorMethod<[], any>,
  '__comments' : ActorMethod<[], any>,
  '__conversations' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<Conversation>
  >,
  '__messages' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<Message>>,
  '__nextBlogId' : ActorMethod<[], any>,
  '__nextCommentId' : ActorMethod<[], any>,
  '__nextConversationId' : ActorMethod<[], any>,
  '__nextMessageId' : ActorMethod<[], any>,
  '__nextNoteId' : ActorMethod<[], any>,
  '__nextNotificationId' : ActorMethod<[], any>,
  '__noteBookmarks' : ActorMethod<[], any>,
  '__noteLikes' : ActorMethod<[], any>,
  '__notes' : ActorMethod<[], any>,
  '__notificationsByUser' : ActorMethod<[], any>,
  '__videoStore' : ActorMethod<[], any>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addComment' : ActorMethod<[BlogId, [] | [CommentId], string], CommentView>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookmarkBlog' : ActorMethod<[BlogId], undefined>,
  'bookmarkNote' : ActorMethod<[bigint], undefined>,
  'bookmarkVideo' : ActorMethod<[VideoId], boolean>,
  'createBlog' : ActorMethod<
    [string, string, string, Array<string>, [] | [Uint8Array], boolean],
    BlogView
  >,
  'createConversation' : ActorMethod<[string], Conversation>,
  'createNote' : ActorMethod<[NoteInput], NoteView>,
  'createNotification' : ActorMethod<
    [Principal, NotificationType, string, [] | [SourceContent]],
    undefined
  >,
  'createVideo' : ActorMethod<[VideoInput], Video>,
  'deleteBlog' : ActorMethod<[BlogId], undefined>,
  'deleteComment' : ActorMethod<[CommentId], undefined>,
  'deleteConversation' : ActorMethod<[bigint], boolean>,
  'deleteNote' : ActorMethod<[bigint], undefined>,
  'deleteVideo' : ActorMethod<[VideoId], boolean>,
  'getBlog' : ActorMethod<[BlogId], [] | [BlogView]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[BlogId], Array<CommentView>>,
  'getCreatorDashboard' : ActorMethod<[], CreatorDashboard>,
  'getMessages' : ActorMethod<[bigint], Array<Message>>,
  'getNote' : ActorMethod<[bigint], [] | [NoteView]>,
  'getRelatedContent' : ActorMethod<
    [
      { 'video' : null } |
        { 'blog' : null } |
        { 'note' : null },
      bigint,
      bigint,
    ],
    Array<Recommendation>
  >,
  'getStudentDashboard' : ActorMethod<[], StudentDashboard>,
  'getTrending' : ActorMethod<[bigint], Array<TrendingItem>>,
  'getVideo' : ActorMethod<[VideoId], [] | [Video]>,
  'incrementDownload' : ActorMethod<[bigint], undefined>,
  'incrementView' : ActorMethod<[VideoId, string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isVideoBookmarked' : ActorMethod<[VideoId], boolean>,
  'isVideoLiked' : ActorMethod<[VideoId], boolean>,
  'likeBlog' : ActorMethod<[BlogId], undefined>,
  'likeComment' : ActorMethod<[CommentId], undefined>,
  'likeNote' : ActorMethod<[bigint], undefined>,
  'likeVideo' : ActorMethod<[VideoId], boolean>,
  'listBlogs' : ActorMethod<[ListBlogsQuery], ListBlogsResult>,
  'listConversations' : ActorMethod<[], Array<Conversation>>,
  'listNotes' : ActorMethod<[NoteListQuery], NoteListResult>,
  'listNotifications' : ActorMethod<[], ListNotificationsResult>,
  'listVideos' : ActorMethod<[VideoFilter], VideoPage>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markNotificationRead' : ActorMethod<[NotificationId], undefined>,
  'sendMessage' : ActorMethod<[bigint, string], SendMessageResult>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unbookmarkBlog' : ActorMethod<[BlogId], undefined>,
  'unbookmarkNote' : ActorMethod<[bigint], undefined>,
  'unbookmarkVideo' : ActorMethod<[VideoId], boolean>,
  'unlikeBlog' : ActorMethod<[BlogId], undefined>,
  'unlikeNote' : ActorMethod<[bigint], undefined>,
  'unlikeVideo' : ActorMethod<[VideoId], boolean>,
  'updateBlog' : ActorMethod<
    [BlogId, string, string, string, Array<string>, [] | [Uint8Array], boolean],
    BlogView
  >,
  'updateNote' : ActorMethod<[bigint, NoteUpdate], NoteView>,
  'updateVideo' : ActorMethod<[VideoId, VideoUpdate], [] | [Video]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];