/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Nat;
export const UserId = IDL.Principal;
export const Conversation = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'user' : UserId,
  'updatedAt' : Timestamp,
});
export const MessageRole = IDL.Variant({
  'user' : IDL.Null,
  'assistant' : IDL.Null,
});
export const SourceType = IDL.Variant({
  'video' : IDL.Null,
  'blog' : IDL.Null,
  'note' : IDL.Null,
});
export const SourceReference = IDL.Record({
  'title' : IDL.Text,
  'contentId' : IDL.Nat,
  'sourceType' : SourceType,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : MessageRole,
  'conversationId' : IDL.Nat,
  'sources' : IDL.Vec(SourceReference),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const BlogId = IDL.Nat;
export const CommentId = IDL.Nat;
export const CommentView = IDL.Record({
  'id' : CommentId,
  'likeCount' : IDL.Nat,
  'content' : IDL.Text,
  'parentCommentId' : IDL.Opt(CommentId),
  'createdAt' : Timestamp,
  'author' : IDL.Principal,
  'blogId' : BlogId,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const VideoId = IDL.Nat;
export const BlogView = IDL.Record({
  'id' : BlogId,
  'title' : IDL.Text,
  'likeCount' : IDL.Nat,
  'content' : IDL.Text,
  'published' : IDL.Bool,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'author' : IDL.Principal,
  'updatedAt' : Timestamp,
  'viewCount' : IDL.Nat,
  'excerpt' : IDL.Text,
  'coverImageBlobId' : IDL.Opt(IDL.Vec(IDL.Nat8)),
});
export const NoteFileType = IDL.Variant({
  'pdf' : IDL.Null,
  'ppt' : IDL.Null,
  'zip' : IDL.Null,
  'docx' : IDL.Null,
});
export const NoteInput = IDL.Record({
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'published' : IDL.Bool,
  'description' : IDL.Text,
  'fileSize' : IDL.Nat,
  'fileType' : NoteFileType,
  'blobId' : IDL.Text,
});
export const NoteView = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'likeCount' : IDL.Nat,
  'subject' : IDL.Text,
  'published' : IDL.Bool,
  'createdAt' : IDL.Nat,
  'description' : IDL.Text,
  'fileSize' : IDL.Nat,
  'fileType' : NoteFileType,
  'author' : IDL.Principal,
  'updatedAt' : IDL.Nat,
  'blobId' : IDL.Text,
  'downloadCount' : IDL.Nat,
});
export const NotificationType = IDL.Variant({
  'like' : IDL.Null,
  'systemMessage' : IDL.Null,
  'comment' : IDL.Null,
  'roleUpgrade' : IDL.Null,
  'moderation' : IDL.Null,
});
export const SourceContent = IDL.Record({
  'id' : IDL.Nat,
  'contentType' : IDL.Text,
});
export const Category = IDL.Text;
export const VideoInput = IDL.Record({
  'title' : IDL.Text,
  'isShort' : IDL.Bool,
  'videoBlobId' : IDL.Text,
  'thumbnailBlobId' : IDL.Text,
  'published' : IDL.Bool,
  'description' : IDL.Text,
  'durationSeconds' : IDL.Nat,
  'category' : Category,
});
export const Video = IDL.Record({
  'id' : VideoId,
  'title' : IDL.Text,
  'likeCount' : IDL.Nat,
  'isShort' : IDL.Bool,
  'videoBlobId' : IDL.Text,
  'thumbnailBlobId' : IDL.Text,
  'published' : IDL.Bool,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'author' : IDL.Principal,
  'updatedAt' : IDL.Int,
  'viewCount' : IDL.Nat,
  'durationSeconds' : IDL.Nat,
  'category' : Category,
});
export const ContentType = IDL.Variant({
  'video' : IDL.Null,
  'blog' : IDL.Null,
  'note' : IDL.Null,
});
export const ContentPerformanceItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'trend' : IDL.Int,
  'contentType' : ContentType,
  'views' : IDL.Nat,
  'likes' : IDL.Nat,
  'comments' : IDL.Nat,
});
export const CreatorViewsByTypePoint = IDL.Record({
  'videoViews' : IDL.Nat,
  'date' : IDL.Text,
  'noteViews' : IDL.Nat,
  'blogViews' : IDL.Nat,
});
export const RecentCommentItem = IDL.Record({
  'contentId' : IDL.Nat,
  'content' : IDL.Text,
  'commentId' : IDL.Nat,
  'contentType' : ContentType,
  'createdAt' : Timestamp,
  'author' : IDL.Principal,
  'contentTitle' : IDL.Text,
});
export const EngagementByType = IDL.Record({
  'contentType' : ContentType,
  'bookmarks' : IDL.Nat,
  'likes' : IDL.Nat,
  'comments' : IDL.Nat,
});
export const CreatorTotals = IDL.Record({
  'contentCount' : IDL.Nat,
  'totalBookmarks' : IDL.Nat,
  'totalViews' : IDL.Nat,
  'totalLikes' : IDL.Nat,
});
export const CreatorDashboard = IDL.Record({
  'contentPerformance' : IDL.Vec(ContentPerformanceItem),
  'viewsOverTime' : IDL.Vec(CreatorViewsByTypePoint),
  'recentComments' : IDL.Vec(RecentCommentItem),
  'engagementByType' : IDL.Vec(EngagementByType),
  'totals' : CreatorTotals,
});
export const Recommendation = IDL.Record({
  'contentRef' : IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'contentType' : IDL.Variant({
      'video' : IDL.Null,
      'blog' : IDL.Null,
      'note' : IDL.Null,
    }),
    'author' : IDL.Principal,
  }),
  'score' : IDL.Float64,
  'reason' : IDL.Text,
});
export const ContentRef = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'contentType' : ContentType,
  'author' : IDL.Principal,
});
export const BookmarkItem = IDL.Record({
  'content' : ContentRef,
  'bookmarkedAt' : Timestamp,
});
export const AIConversationSummary = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'lastMessageAt' : Timestamp,
  'messageCount' : IDL.Nat,
});
export const StudentTotals = IDL.Record({
  'aiConversationsCount' : IDL.Nat,
  'likedContentCount' : IDL.Nat,
  'bookmarksCount' : IDL.Nat,
});
export const StudentActivityPoint = IDL.Record({
  'date' : IDL.Text,
  'bookmarks' : IDL.Nat,
  'likes' : IDL.Nat,
  'aiSessions' : IDL.Nat,
});
export const StudentDashboard = IDL.Record({
  'bookmarks' : IDL.Vec(BookmarkItem),
  'recentAIConversations' : IDL.Vec(AIConversationSummary),
  'totals' : StudentTotals,
  'learningActivityOverTime' : IDL.Vec(StudentActivityPoint),
});
export const TrendingItem = IDL.Record({
  'views' : IDL.Nat,
  'contentRef' : IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'contentType' : IDL.Variant({
      'video' : IDL.Null,
      'blog' : IDL.Null,
      'note' : IDL.Null,
    }),
    'author' : IDL.Principal,
  }),
  'likes' : IDL.Nat,
  'score' : IDL.Float64,
});
export const BlogSort = IDL.Variant({
  'mostBookmarked' : IDL.Null,
  'newest' : IDL.Null,
  'mostLiked' : IDL.Null,
  'mostViewed' : IDL.Null,
});
export const ListBlogsQuery = IDL.Record({
  'tag' : IDL.Opt(IDL.Text),
  'page' : IDL.Nat,
  'sort' : BlogSort,
  'pageSize' : IDL.Nat,
  'search' : IDL.Opt(IDL.Text),
});
export const ListBlogsResult = IDL.Record({
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'items' : IDL.Vec(BlogView),
});
export const NoteSort = IDL.Variant({
  'mostBookmarked' : IDL.Null,
  'mostDownloaded' : IDL.Null,
  'newest' : IDL.Null,
  'mostLiked' : IDL.Null,
});
export const NoteListQuery = IDL.Record({
  'subject' : IDL.Opt(IDL.Text),
  'page' : IDL.Nat,
  'sort' : IDL.Opt(NoteSort),
  'pageSize' : IDL.Nat,
  'search' : IDL.Opt(IDL.Text),
  'fileType' : IDL.Opt(NoteFileType),
});
export const NoteListResult = IDL.Record({
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'items' : IDL.Vec(NoteView),
});
export const NotificationId = IDL.Nat;
export const NotificationView = IDL.Record({
  'id' : NotificationId,
  'content' : IDL.Text,
  'source' : IDL.Opt(SourceContent),
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'read' : IDL.Bool,
  'recipient' : IDL.Principal,
});
export const ListNotificationsResult = IDL.Record({
  'unreadCount' : IDL.Nat,
  'items' : IDL.Vec(NotificationView),
});
export const VideoSort = IDL.Variant({
  'mostBookmarked' : IDL.Null,
  'newest' : IDL.Null,
  'mostLiked' : IDL.Null,
  'mostViewed' : IDL.Null,
});
export const VideoFilter = IDL.Record({
  'isShort' : IDL.Opt(IDL.Bool),
  'page' : IDL.Opt(IDL.Nat),
  'sort' : IDL.Opt(VideoSort),
  'pageSize' : IDL.Opt(IDL.Nat),
  'search' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(Category),
});
export const VideoPage = IDL.Record({
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'items' : IDL.Vec(Video),
});
export const SendMessageResult = IDL.Record({
  'message' : Message,
  'sources' : IDL.Vec(SourceReference),
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpRequestResult = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpRequestResult,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const NoteUpdate = IDL.Record({
  'title' : IDL.Opt(IDL.Text),
  'subject' : IDL.Opt(IDL.Text),
  'published' : IDL.Opt(IDL.Bool),
  'description' : IDL.Opt(IDL.Text),
  'fileSize' : IDL.Opt(IDL.Nat),
  'fileType' : IDL.Opt(NoteFileType),
  'blobId' : IDL.Opt(IDL.Text),
});
export const VideoUpdate = IDL.Record({
  'title' : IDL.Opt(IDL.Text),
  'isShort' : IDL.Opt(IDL.Bool),
  'thumbnailBlobId' : IDL.Opt(IDL.Text),
  'published' : IDL.Opt(IDL.Bool),
  'description' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(Category),
});

export const idlService = IDL.Service({
  '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__blogBookmarks' : IDL.Func([], [IDL.Reserved], ['query']),
  '__blogLikes' : IDL.Func([], [IDL.Reserved], ['query']),
  '__blogs' : IDL.Func([], [IDL.Reserved], ['query']),
  '__commentLikes' : IDL.Func([], [IDL.Reserved], ['query']),
  '__comments' : IDL.Func([], [IDL.Reserved], ['query']),
  '__conversations' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Conversation)],
      ['query'],
    ),
  '__messages' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Message)],
      ['query'],
    ),
  '__nextBlogId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextCommentId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextConversationId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextMessageId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextNoteId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextNotificationId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__noteBookmarks' : IDL.Func([], [IDL.Reserved], ['query']),
  '__noteLikes' : IDL.Func([], [IDL.Reserved], ['query']),
  '__notes' : IDL.Func([], [IDL.Reserved], ['query']),
  '__notificationsByUser' : IDL.Func([], [IDL.Reserved], ['query']),
  '__videoStore' : IDL.Func([], [IDL.Reserved], ['query']),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addComment' : IDL.Func(
      [BlogId, IDL.Opt(CommentId), IDL.Text],
      [CommentView],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookmarkBlog' : IDL.Func([BlogId], [], []),
  'bookmarkNote' : IDL.Func([IDL.Nat], [], []),
  'bookmarkVideo' : IDL.Func([VideoId], [IDL.Bool], []),
  'createBlog' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Vec(IDL.Nat8)),
        IDL.Bool,
      ],
      [BlogView],
      [],
    ),
  'createConversation' : IDL.Func([IDL.Text], [Conversation], []),
  'createNote' : IDL.Func([NoteInput], [NoteView], []),
  'createNotification' : IDL.Func(
      [IDL.Principal, NotificationType, IDL.Text, IDL.Opt(SourceContent)],
      [],
      [],
    ),
  'createVideo' : IDL.Func([VideoInput], [Video], []),
  'deleteBlog' : IDL.Func([BlogId], [], []),
  'deleteComment' : IDL.Func([CommentId], [], []),
  'deleteConversation' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteNote' : IDL.Func([IDL.Nat], [], []),
  'deleteVideo' : IDL.Func([VideoId], [IDL.Bool], []),
  'getBlog' : IDL.Func([BlogId], [IDL.Opt(BlogView)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([BlogId], [IDL.Vec(CommentView)], ['query']),
  'getCreatorDashboard' : IDL.Func([], [CreatorDashboard], []),
  'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], []),
  'getNote' : IDL.Func([IDL.Nat], [IDL.Opt(NoteView)], ['query']),
  'getRelatedContent' : IDL.Func(
      [
        IDL.Variant({
          'video' : IDL.Null,
          'blog' : IDL.Null,
          'note' : IDL.Null,
        }),
        IDL.Nat,
        IDL.Nat,
      ],
      [IDL.Vec(Recommendation)],
      ['query'],
    ),
  'getStudentDashboard' : IDL.Func([], [StudentDashboard], []),
  'getTrending' : IDL.Func([IDL.Nat], [IDL.Vec(TrendingItem)], ['query']),
  'getVideo' : IDL.Func([VideoId], [IDL.Opt(Video)], ['query']),
  'incrementDownload' : IDL.Func([IDL.Nat], [], []),
  'incrementView' : IDL.Func([VideoId, IDL.Text], [IDL.Bool], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isVideoBookmarked' : IDL.Func([VideoId], [IDL.Bool], []),
  'isVideoLiked' : IDL.Func([VideoId], [IDL.Bool], []),
  'likeBlog' : IDL.Func([BlogId], [], []),
  'likeComment' : IDL.Func([CommentId], [], []),
  'likeNote' : IDL.Func([IDL.Nat], [], []),
  'likeVideo' : IDL.Func([VideoId], [IDL.Bool], []),
  'listBlogs' : IDL.Func([ListBlogsQuery], [ListBlogsResult], ['query']),
  'listConversations' : IDL.Func([], [IDL.Vec(Conversation)], []),
  'listNotes' : IDL.Func([NoteListQuery], [NoteListResult], ['query']),
  'listNotifications' : IDL.Func([], [ListNotificationsResult], []),
  'listVideos' : IDL.Func([VideoFilter], [VideoPage], ['query']),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markNotificationRead' : IDL.Func([NotificationId], [], []),
  'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [SendMessageResult], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unbookmarkBlog' : IDL.Func([BlogId], [], []),
  'unbookmarkNote' : IDL.Func([IDL.Nat], [], []),
  'unbookmarkVideo' : IDL.Func([VideoId], [IDL.Bool], []),
  'unlikeBlog' : IDL.Func([BlogId], [], []),
  'unlikeNote' : IDL.Func([IDL.Nat], [], []),
  'unlikeVideo' : IDL.Func([VideoId], [IDL.Bool], []),
  'updateBlog' : IDL.Func(
      [
        BlogId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Vec(IDL.Nat8)),
        IDL.Bool,
      ],
      [BlogView],
      [],
    ),
  'updateNote' : IDL.Func([IDL.Nat, NoteUpdate], [NoteView], []),
  'updateVideo' : IDL.Func([VideoId, VideoUpdate], [IDL.Opt(Video)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Nat;
  const UserId = IDL.Principal;
  const Conversation = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'user' : UserId,
    'updatedAt' : Timestamp,
  });
  const MessageRole = IDL.Variant({
    'user' : IDL.Null,
    'assistant' : IDL.Null,
  });
  const SourceType = IDL.Variant({
    'video' : IDL.Null,
    'blog' : IDL.Null,
    'note' : IDL.Null,
  });
  const SourceReference = IDL.Record({
    'title' : IDL.Text,
    'contentId' : IDL.Nat,
    'sourceType' : SourceType,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : MessageRole,
    'conversationId' : IDL.Nat,
    'sources' : IDL.Vec(SourceReference),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const BlogId = IDL.Nat;
  const CommentId = IDL.Nat;
  const CommentView = IDL.Record({
    'id' : CommentId,
    'likeCount' : IDL.Nat,
    'content' : IDL.Text,
    'parentCommentId' : IDL.Opt(CommentId),
    'createdAt' : Timestamp,
    'author' : IDL.Principal,
    'blogId' : BlogId,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const VideoId = IDL.Nat;
  const BlogView = IDL.Record({
    'id' : BlogId,
    'title' : IDL.Text,
    'likeCount' : IDL.Nat,
    'content' : IDL.Text,
    'published' : IDL.Bool,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'author' : IDL.Principal,
    'updatedAt' : Timestamp,
    'viewCount' : IDL.Nat,
    'excerpt' : IDL.Text,
    'coverImageBlobId' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  });
  const NoteFileType = IDL.Variant({
    'pdf' : IDL.Null,
    'ppt' : IDL.Null,
    'zip' : IDL.Null,
    'docx' : IDL.Null,
  });
  const NoteInput = IDL.Record({
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'published' : IDL.Bool,
    'description' : IDL.Text,
    'fileSize' : IDL.Nat,
    'fileType' : NoteFileType,
    'blobId' : IDL.Text,
  });
  const NoteView = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'likeCount' : IDL.Nat,
    'subject' : IDL.Text,
    'published' : IDL.Bool,
    'createdAt' : IDL.Nat,
    'description' : IDL.Text,
    'fileSize' : IDL.Nat,
    'fileType' : NoteFileType,
    'author' : IDL.Principal,
    'updatedAt' : IDL.Nat,
    'blobId' : IDL.Text,
    'downloadCount' : IDL.Nat,
  });
  const NotificationType = IDL.Variant({
    'like' : IDL.Null,
    'systemMessage' : IDL.Null,
    'comment' : IDL.Null,
    'roleUpgrade' : IDL.Null,
    'moderation' : IDL.Null,
  });
  const SourceContent = IDL.Record({
    'id' : IDL.Nat,
    'contentType' : IDL.Text,
  });
  const Category = IDL.Text;
  const VideoInput = IDL.Record({
    'title' : IDL.Text,
    'isShort' : IDL.Bool,
    'videoBlobId' : IDL.Text,
    'thumbnailBlobId' : IDL.Text,
    'published' : IDL.Bool,
    'description' : IDL.Text,
    'durationSeconds' : IDL.Nat,
    'category' : Category,
  });
  const Video = IDL.Record({
    'id' : VideoId,
    'title' : IDL.Text,
    'likeCount' : IDL.Nat,
    'isShort' : IDL.Bool,
    'videoBlobId' : IDL.Text,
    'thumbnailBlobId' : IDL.Text,
    'published' : IDL.Bool,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'author' : IDL.Principal,
    'updatedAt' : IDL.Int,
    'viewCount' : IDL.Nat,
    'durationSeconds' : IDL.Nat,
    'category' : Category,
  });
  const ContentType = IDL.Variant({
    'video' : IDL.Null,
    'blog' : IDL.Null,
    'note' : IDL.Null,
  });
  const ContentPerformanceItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'trend' : IDL.Int,
    'contentType' : ContentType,
    'views' : IDL.Nat,
    'likes' : IDL.Nat,
    'comments' : IDL.Nat,
  });
  const CreatorViewsByTypePoint = IDL.Record({
    'videoViews' : IDL.Nat,
    'date' : IDL.Text,
    'noteViews' : IDL.Nat,
    'blogViews' : IDL.Nat,
  });
  const RecentCommentItem = IDL.Record({
    'contentId' : IDL.Nat,
    'content' : IDL.Text,
    'commentId' : IDL.Nat,
    'contentType' : ContentType,
    'createdAt' : Timestamp,
    'author' : IDL.Principal,
    'contentTitle' : IDL.Text,
  });
  const EngagementByType = IDL.Record({
    'contentType' : ContentType,
    'bookmarks' : IDL.Nat,
    'likes' : IDL.Nat,
    'comments' : IDL.Nat,
  });
  const CreatorTotals = IDL.Record({
    'contentCount' : IDL.Nat,
    'totalBookmarks' : IDL.Nat,
    'totalViews' : IDL.Nat,
    'totalLikes' : IDL.Nat,
  });
  const CreatorDashboard = IDL.Record({
    'contentPerformance' : IDL.Vec(ContentPerformanceItem),
    'viewsOverTime' : IDL.Vec(CreatorViewsByTypePoint),
    'recentComments' : IDL.Vec(RecentCommentItem),
    'engagementByType' : IDL.Vec(EngagementByType),
    'totals' : CreatorTotals,
  });
  const Recommendation = IDL.Record({
    'contentRef' : IDL.Record({
      'id' : IDL.Nat,
      'title' : IDL.Text,
      'contentType' : IDL.Variant({
        'video' : IDL.Null,
        'blog' : IDL.Null,
        'note' : IDL.Null,
      }),
      'author' : IDL.Principal,
    }),
    'score' : IDL.Float64,
    'reason' : IDL.Text,
  });
  const ContentRef = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'contentType' : ContentType,
    'author' : IDL.Principal,
  });
  const BookmarkItem = IDL.Record({
    'content' : ContentRef,
    'bookmarkedAt' : Timestamp,
  });
  const AIConversationSummary = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'lastMessageAt' : Timestamp,
    'messageCount' : IDL.Nat,
  });
  const StudentTotals = IDL.Record({
    'aiConversationsCount' : IDL.Nat,
    'likedContentCount' : IDL.Nat,
    'bookmarksCount' : IDL.Nat,
  });
  const StudentActivityPoint = IDL.Record({
    'date' : IDL.Text,
    'bookmarks' : IDL.Nat,
    'likes' : IDL.Nat,
    'aiSessions' : IDL.Nat,
  });
  const StudentDashboard = IDL.Record({
    'bookmarks' : IDL.Vec(BookmarkItem),
    'recentAIConversations' : IDL.Vec(AIConversationSummary),
    'totals' : StudentTotals,
    'learningActivityOverTime' : IDL.Vec(StudentActivityPoint),
  });
  const TrendingItem = IDL.Record({
    'views' : IDL.Nat,
    'contentRef' : IDL.Record({
      'id' : IDL.Nat,
      'title' : IDL.Text,
      'contentType' : IDL.Variant({
        'video' : IDL.Null,
        'blog' : IDL.Null,
        'note' : IDL.Null,
      }),
      'author' : IDL.Principal,
    }),
    'likes' : IDL.Nat,
    'score' : IDL.Float64,
  });
  const BlogSort = IDL.Variant({
    'mostBookmarked' : IDL.Null,
    'newest' : IDL.Null,
    'mostLiked' : IDL.Null,
    'mostViewed' : IDL.Null,
  });
  const ListBlogsQuery = IDL.Record({
    'tag' : IDL.Opt(IDL.Text),
    'page' : IDL.Nat,
    'sort' : BlogSort,
    'pageSize' : IDL.Nat,
    'search' : IDL.Opt(IDL.Text),
  });
  const ListBlogsResult = IDL.Record({
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'items' : IDL.Vec(BlogView),
  });
  const NoteSort = IDL.Variant({
    'mostBookmarked' : IDL.Null,
    'mostDownloaded' : IDL.Null,
    'newest' : IDL.Null,
    'mostLiked' : IDL.Null,
  });
  const NoteListQuery = IDL.Record({
    'subject' : IDL.Opt(IDL.Text),
    'page' : IDL.Nat,
    'sort' : IDL.Opt(NoteSort),
    'pageSize' : IDL.Nat,
    'search' : IDL.Opt(IDL.Text),
    'fileType' : IDL.Opt(NoteFileType),
  });
  const NoteListResult = IDL.Record({
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'items' : IDL.Vec(NoteView),
  });
  const NotificationId = IDL.Nat;
  const NotificationView = IDL.Record({
    'id' : NotificationId,
    'content' : IDL.Text,
    'source' : IDL.Opt(SourceContent),
    'notificationType' : NotificationType,
    'createdAt' : Timestamp,
    'read' : IDL.Bool,
    'recipient' : IDL.Principal,
  });
  const ListNotificationsResult = IDL.Record({
    'unreadCount' : IDL.Nat,
    'items' : IDL.Vec(NotificationView),
  });
  const VideoSort = IDL.Variant({
    'mostBookmarked' : IDL.Null,
    'newest' : IDL.Null,
    'mostLiked' : IDL.Null,
    'mostViewed' : IDL.Null,
  });
  const VideoFilter = IDL.Record({
    'isShort' : IDL.Opt(IDL.Bool),
    'page' : IDL.Opt(IDL.Nat),
    'sort' : IDL.Opt(VideoSort),
    'pageSize' : IDL.Opt(IDL.Nat),
    'search' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(Category),
  });
  const VideoPage = IDL.Record({
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'items' : IDL.Vec(Video),
  });
  const SendMessageResult = IDL.Record({
    'message' : Message,
    'sources' : IDL.Vec(SourceReference),
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpRequestResult = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpRequestResult,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const NoteUpdate = IDL.Record({
    'title' : IDL.Opt(IDL.Text),
    'subject' : IDL.Opt(IDL.Text),
    'published' : IDL.Opt(IDL.Bool),
    'description' : IDL.Opt(IDL.Text),
    'fileSize' : IDL.Opt(IDL.Nat),
    'fileType' : IDL.Opt(NoteFileType),
    'blobId' : IDL.Opt(IDL.Text),
  });
  const VideoUpdate = IDL.Record({
    'title' : IDL.Opt(IDL.Text),
    'isShort' : IDL.Opt(IDL.Bool),
    'thumbnailBlobId' : IDL.Opt(IDL.Text),
    'published' : IDL.Opt(IDL.Bool),
    'description' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(Category),
  });
  
  return IDL.Service({
    '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__blogBookmarks' : IDL.Func([], [IDL.Reserved], ['query']),
    '__blogLikes' : IDL.Func([], [IDL.Reserved], ['query']),
    '__blogs' : IDL.Func([], [IDL.Reserved], ['query']),
    '__commentLikes' : IDL.Func([], [IDL.Reserved], ['query']),
    '__comments' : IDL.Func([], [IDL.Reserved], ['query']),
    '__conversations' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Conversation)],
        ['query'],
      ),
    '__messages' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Message)],
        ['query'],
      ),
    '__nextBlogId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextCommentId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextConversationId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextMessageId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextNoteId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextNotificationId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__noteBookmarks' : IDL.Func([], [IDL.Reserved], ['query']),
    '__noteLikes' : IDL.Func([], [IDL.Reserved], ['query']),
    '__notes' : IDL.Func([], [IDL.Reserved], ['query']),
    '__notificationsByUser' : IDL.Func([], [IDL.Reserved], ['query']),
    '__videoStore' : IDL.Func([], [IDL.Reserved], ['query']),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addComment' : IDL.Func(
        [BlogId, IDL.Opt(CommentId), IDL.Text],
        [CommentView],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookmarkBlog' : IDL.Func([BlogId], [], []),
    'bookmarkNote' : IDL.Func([IDL.Nat], [], []),
    'bookmarkVideo' : IDL.Func([VideoId], [IDL.Bool], []),
    'createBlog' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Vec(IDL.Nat8)),
          IDL.Bool,
        ],
        [BlogView],
        [],
      ),
    'createConversation' : IDL.Func([IDL.Text], [Conversation], []),
    'createNote' : IDL.Func([NoteInput], [NoteView], []),
    'createNotification' : IDL.Func(
        [IDL.Principal, NotificationType, IDL.Text, IDL.Opt(SourceContent)],
        [],
        [],
      ),
    'createVideo' : IDL.Func([VideoInput], [Video], []),
    'deleteBlog' : IDL.Func([BlogId], [], []),
    'deleteComment' : IDL.Func([CommentId], [], []),
    'deleteConversation' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteNote' : IDL.Func([IDL.Nat], [], []),
    'deleteVideo' : IDL.Func([VideoId], [IDL.Bool], []),
    'getBlog' : IDL.Func([BlogId], [IDL.Opt(BlogView)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([BlogId], [IDL.Vec(CommentView)], ['query']),
    'getCreatorDashboard' : IDL.Func([], [CreatorDashboard], []),
    'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], []),
    'getNote' : IDL.Func([IDL.Nat], [IDL.Opt(NoteView)], ['query']),
    'getRelatedContent' : IDL.Func(
        [
          IDL.Variant({
            'video' : IDL.Null,
            'blog' : IDL.Null,
            'note' : IDL.Null,
          }),
          IDL.Nat,
          IDL.Nat,
        ],
        [IDL.Vec(Recommendation)],
        ['query'],
      ),
    'getStudentDashboard' : IDL.Func([], [StudentDashboard], []),
    'getTrending' : IDL.Func([IDL.Nat], [IDL.Vec(TrendingItem)], ['query']),
    'getVideo' : IDL.Func([VideoId], [IDL.Opt(Video)], ['query']),
    'incrementDownload' : IDL.Func([IDL.Nat], [], []),
    'incrementView' : IDL.Func([VideoId, IDL.Text], [IDL.Bool], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isVideoBookmarked' : IDL.Func([VideoId], [IDL.Bool], []),
    'isVideoLiked' : IDL.Func([VideoId], [IDL.Bool], []),
    'likeBlog' : IDL.Func([BlogId], [], []),
    'likeComment' : IDL.Func([CommentId], [], []),
    'likeNote' : IDL.Func([IDL.Nat], [], []),
    'likeVideo' : IDL.Func([VideoId], [IDL.Bool], []),
    'listBlogs' : IDL.Func([ListBlogsQuery], [ListBlogsResult], ['query']),
    'listConversations' : IDL.Func([], [IDL.Vec(Conversation)], []),
    'listNotes' : IDL.Func([NoteListQuery], [NoteListResult], ['query']),
    'listNotifications' : IDL.Func([], [ListNotificationsResult], []),
    'listVideos' : IDL.Func([VideoFilter], [VideoPage], ['query']),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markNotificationRead' : IDL.Func([NotificationId], [], []),
    'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [SendMessageResult], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unbookmarkBlog' : IDL.Func([BlogId], [], []),
    'unbookmarkNote' : IDL.Func([IDL.Nat], [], []),
    'unbookmarkVideo' : IDL.Func([VideoId], [IDL.Bool], []),
    'unlikeBlog' : IDL.Func([BlogId], [], []),
    'unlikeNote' : IDL.Func([IDL.Nat], [], []),
    'unlikeVideo' : IDL.Func([VideoId], [IDL.Bool], []),
    'updateBlog' : IDL.Func(
        [
          BlogId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Vec(IDL.Nat8)),
          IDL.Bool,
        ],
        [BlogView],
        [],
      ),
    'updateNote' : IDL.Func([IDL.Nat, NoteUpdate], [NoteView], []),
    'updateVideo' : IDL.Func([VideoId, VideoUpdate], [IDL.Opt(Video)], []),
  });
};

export const init = ({ IDL }) => { return []; };